### ISSUE TITLE
meta doesn't support conditionals

### ISSUE THREAD

**Issue by benklop** [wcm-io-devops/ansible-jenkins-plugins#8] opened 2020-06-25 19:18 UTC
See https://github.com/ansible/ansible/issues/41313 - for this reason, the tasks are always run at https://github.com/wcm-io-devops/ansible-jenkins-plugins/blob/master/tasks/main.yml#L46-L48. I have another role that adds a handler that restarts jenkins, and makes this role subsequently fail. At least add a wait like at https://github.com/geerlingguy/ansible-role-jenkins/blob/master/tasks/main.yml#L35-L49 to make sure jenkins is fully operational before continuing.

**Comment by tobias-richter** [comment] 2020-07-13 10:36
@benklop I was not aware of the mentioned issue. On our side we have never experienced this issue, maybe because we are using Ansible 2.7.x and not Ansible 2.4.

The role wcm_io_devops.jenkins_plugins depends on the role "wcm_io_devops.jenkins_service" (https://github.com/wcm-io-devops/ansible-jenkins-service) and the restart/wait logic you mentioned is part of the handler implemented there. Without digging any further at the moment I suggest to ensure that no pending restart handler is in the queue before applying the role.

In our setup we are also using the geerlingguy jenkins role in order to setup the jenkins and we have never experienced an issue with the combination of these roles.

**Comment by benklop** [comment] 2020-07-13 22:30
I'm also on ansible 2.7, so I don't think that's that cause of the issue. I'm unsure why it's an issue in my usage, and not in your case.

**Comment by tobias-richter** [comment] 2020-07-14 07:30
@benklop can you provide a skeleton of your playbook so I am able to reproduce?

**Comment by timblaktu** [comment] 2020-07-29 04:07
I should soon be able to provide another datapoint as I am about to start using this role for managing plugins on my masters. I have been having a very hard time getting geerlingguy/ansible-role-jenkins to manage plugins properly, most of which I've traced to its use of ansible's jenkins_plugin module which has several known problems. 

Multiple paths have led me here and I plan tomorrow to modify my jenkins master playbook so that geerlingguy/ansible-role-jenkins installs NO plugins, and then invoke wcm-io-devops/ansible-jenkins-plugins afterwards. @tobias-richter, is this the basic approach you use to provision jenkins masters? Thanks.

**Comment by tobias-richter** [comment] 2020-07-29 06:13
@timblaktu absolutely. You can have a look at https://github.com/wcm-io-devops/ansible-jenkins-pipeline-library for an example how we do it.
I recommend to setup a mirror of the jenkins update site near your masters to speed up the installation if you spin up new masters often.

Feedback and contributions are appreciated ;)

**Comment by timblaktu** [comment] 2020-07-29 17:07
Thanks @tobias-richter. I took a quick look at that role, and it looks like it might supercede mine. I notice you also have a casc role. I've been having a lot of trouble getting active-directory and casc plugins installed and configured automatically, so I might just try using your completely. I'll post there if I have any problems. Is there another place better for asking questions than github issues?

**Comment by tobias-richter** [comment] 2020-07-30 08:06
@timblaktu github issues is totally fine. But perhaps you create a new issues for your questions since you are currently posting in the issue from @benklop.

Short answer regarding the ansible roles you asked for. 
We are maintaining two Jenkins libraries:

https://github.com/wcm-io-devops/jenkins-pipeline-library, which is part of https://devops.wcm.io/ and provides some basic common steps of our pipelines.

and

https://github.com/pro-vision/jenkins-pv-pipeline-library, which extends the first library with our best practices for maven projects.

Since there were some issues in the past regarding script security, bugs in the jenkins groovy sandbox etc. we build up the matching ansible roles to setup jenkins instances with a fixed version, plugin and script security set to be able to deploy the same setup for clients.

The last role pro_vision.jenkins_pv is adding plugins that we are using beside the ones defined in wcm_io_devops.jenkins_pipeline_library and pro_vision.jenkins_pv_pipeline_library.

For any other inquiries please open new issues.

**Comment by tobias-richter** [comment] 2020-08-11 12:02
@benklop I stumbled over the restart during debugging an other issue and I was wondering why I even put a restart there..
So, good news: The restart using the meta flush is removed in the master version. Perhaps you may try the current master version in your setup. When the CI runs of the role are complete I will release a new version.

**Comment by benklop** [comment] 2020-09-25 18:55
@tobias-richter I'll give latest master a try. sorry about the delays in responding, but other concerns have kept me busy for a while. I'll lete you know how it turns out!

**Comment by tobias-richter** [comment] 2020-11-23 18:29
Closing this issue. We can open it again when necessary.

**Closed by tobias-richter** 2020-11-23 18:29 UTC

**Comment by jmnavarrol** [comment] 2022-04-23 11:43
Since https://github.com/ansible/ansible/issues/41313 was closed (unfairly IMHO), I reopened it as https://github.com/ansible/ansible/issues/77616.
